---
# main task for role execution
- name: configure inventory
  hosts: localhost
  gather_facts: no
  
  vars:
    linux_hosts: "{{ survey_hosts.split('\n') }}"  
  
  tasks:
    
  - name: make host group from survey hosts list
    add_host:
      hostname: "{{ item }}"
      groupname: new_group      
    loop: "{{ linux_hosts }}"

- name: install node_exporter
  hosts: new_group,!localhost
  become: true
  gather_facts: true
  
  vars:
    inc_prometheus_config: true
    
  tasks:

    - name: install node exporter
      include_role:
        name: install_node_exporter
    
    - name: configure prometheus
      include_role:
        name: prometheus_config
      when: inc_prometheus_config|bool
      run_once: true
